### ISSUE TITLE
Breaks the Witcher 3

### ISSUE THREAD

**Issue by EL1T3K1LLA** [Vipeax/MSI-LED-Tool#3]
I installed this tool to change the color, since I didn't want the MSI bloatware. I tried to play the Witcher 3 after overclocking, and it wouldn't come up. uninstalled and reinstalled the Witcher, uninstalled and reinstalled different drivers, and restarted my computer a million times. The only thing that worked was removing the tool from the startup. It doesn't interfere with other games as far as I can tell.

**Comment by Vipeax** [comment]
That is interesting. Did the process (Witcher 3) appear in your task manager at that point?

**Comment by EL1T3K1LLA** [comment]
Yup. Basically the screen turns black like it is starting up, and stays that way. I have to alt-tab and close it and the other Witcher process to close it. The Witcher also does that when I start up the MSI Afterburner, which I find to be weird.

**Comment by EL1T3K1LLA** [comment]
I'm very sorry if you spent time trying to fix this issue. I just tried it without Afterburner on (after uninstalling some other possible conflicting programs), and the Witcher opened up just fine. Thank you for responding quickly!
