### ISSUE TITLE
MSI-LED-Tool for Mainboards mystic light

### ISSUE THREAD

**Issue by StealthDefender1** [Vipeax/MSI-LED-Tool#51]
Hello, i stumble upon this tool and think its a good idea.
But in case i have no msi graphics card i was wondering if its possible to control the mystic light on msi boards.
Because the gaming app is crap and the whole overclock and silent mode features are useless.
Thanx for answer....
Greetz Stealth

**Comment by ChriscomIT** [comment]
I love the idea and the program. But I have the same issue as I only have an MSI motherboard (Godlike Gaming) and want to avoid Gaming App bloatware. Can you look into supporting motherboards? Would be super great! Thanks!

**Comment by SapphireMH** [comment]
You can disable the mystic lights in the BIOS of the board.

**Comment by ChriscomIT** [comment]
I don't want to disable Mystic Light. I am looking for an application with a small footprint which can control the mystic light LEDs on the motherboard. Because MSI Gaming App brings a lot of bloatware.

**Comment by SapphireMH** [comment]
@ChriscomIT Disabling it is still better then leaving it at its default colour scheme aint it? 

Nice of you to childishly give a thumbs down while i tried to help.

Now whoever made this tool hasn't responded to this at all, so you're options are the following:
1. Use msi's terrible bloatware.
2. Disable the colours or just live with the default red.
3. Create your own.
4. Wait a currently unknown amount of time for someone else to create it.

**Comment by ChriscomIT** [comment]
Yeah, thanks for the super valuable help (not). It seems u might think ppl have no own brain at all. The only one who acts childish is you sry. BTW how is disabling LEDs anything better? The thought about this topic is to switch colors and lightning patterns without having a software which increments a lot of pieces of software which is mostly not needed as already explained in my previous answer. To disable the LEDs is no option and it's in no way better as default lightning pattern.

JFYI I use suggested methods 1+3 right now. I am still using the MSI bloatware and I am in the process to create my own little app which can do this simple task for me.

Please do something useful and spare us the obviously things next time. Btw I hoped of an answer from the project author to be honest.

**Comment by MinDBreaK** [comment]
Actually creating a custom software for this will require to create a custom kernel driver, which HAS TO be signed with correct certificates. And writing thing like this is quite hard. 
However, if you can run linux, you might want to look into [nagisa/msi-rgb](https://github.com/nagisa/msi-rgb)

**Comment by ChriscomIT** [comment]
@MinDBreaK Hi thanks for the information. You already passed me this information when I asked the same question in your project. So far it's the way I go. It's quite a simple function but getting/writing the signed kernel driver is far away from easy but there is hope. As said I run a Linux machine and as well looked into https://github.com/nagisa/msi-rgb like you recommended me earlier. Anyone else interested might also take a look at https://github.com/SimoDax/MSI-mystic-light-tool. Thanks again!
