### ISSUE TITLE
Update the releases section

### ISSUE THREAD

**Issue by andreycizov** [Vipeax/MSI-LED-Tool#57]
The last version listed does not support 1080 GTX Ti. Probably not a huge fuss for a developer, but could be road-blocking for a user.

**Comment by Cubox-** [comment]
It seems the code has been patched for 1080 Ti
https://github.com/Vipeax/MSI-LED-Tool/commit/437d9d6d6d721a36c3e71bdc4560f4ff253521bc

**Comment by andreycizov** [comment]
No, what I've meant was "the releases section on github project's page does not contain the latest version of the code that works with 1080Ti". The last version over there is dated Sep 2016: https://github.com/Vipeax/MSI-LED-Tool/releases.

I did however compile it myself and it worked with my GPU; but I am not an admin, so it would be nice if someone with access rights took care of it.

**Comment by Cubox-** [comment]
Yeah, I understood what you meant :)

Someone needs to get in touch with the author to get him to give rights to edit the code and/or release section.

**Comment by Vipeax** [comment]
Done.
