### ISSUE TITLE
Increase CurrentThread.Join delay when no animation used

### ISSUE THREAD

**Issue by Cubox-** [Vipeax/MSI-LED-Tool#58]
Updating the LEDs is CPU intensive.
When no animation is used, there is no need to update them so often.
There should be a check here https://github.com/Vipeax/MSI-LED-Tool/blob/master/MSI%20LED%20Tool/Program.cs#L440 to increase this delay if the animation selected is NoAnimation

This would fix high CPU usage on some cases, while keeping users able to use animations

**Comment by Vipeax** [comment]
There is this thing called pull requests, right? ;) I added a sleep elsewhere that should solve this in a better way.

**Comment by Cubox-** [comment]
Thanks.
I did not make a pull request because I did not know how to make those changes in a way that was clean/not a hack.

Cheers!
