### ISSUE TITLE
Not going back to default when killing the MSI LED Tool process?!

### ISSUE THREAD

**Issue by tumas04** [Vipeax/MSI-LED-Tool#6]
I am not sure if this really is an issue or not, but i somehow was expecting my card to go back to default (white LED) when closing/killing the MSI LED Tool process. If i kill that process, my cards LEDs are just completely off (even after rebooting the system and without the tool beeing autostarted) instead of the expected white LED. Is this intentional? I mean, it is a kind of a nice way to have no LEDs at all even without running a program in the background all the time, but it still feels "wrong" ;)

**Comment by Vipeax** [comment]
To make them white the application would actually commit a white-LED request prior to closing. Blame MSI for that 💃 ...
